### PR TITLE
asyncAwait

### PR DESCRIPTION
**Pull request by lorengreenfield**

### CODE REVIEW

**Comment by 75lb** [comment]
Perfect, thanks. 👌

**Comment by 75lb** [comment]
Released in v1.5.0.

**Comment by lorengreenfield** [comment]
My pleasure!

**Comment by 75lb** [comment]
FYI, the email address you commit with (lgreenfield@mtruapehu.com) is not associated with your Github account so you don't show as a [contributor](https://github.com/75lb/feature-detect-es6/graphs/contributors) on the project. If you associate the email you should show up correctly.

**Comment by lorengreenfield** [comment]
Doh! Thanks, my work machine had my work email in my git settings.

**Pull request merged**
